name: client_server_lan
description: A simple to use LAN communication package. The Server and a Client can freely distribute data over LAN.
version: 1.1.0
homepage: https://github.com/Robert3141/client_server_lan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: 
  isohttpd:
    path: ../isohttpd
    # git:
    #   url: https://github.com/Xdrop-app/isohttpd.git
  meta: 
  emodebug: 